    server:
      port: 8082


    spring:
      datasource:
        url: jdbc:mysql://localhost:3306/microservices_tables
        username: root
        password: root
      application:
        name: HOSPITAL-SERVICE


      jpa:
        hibernate:
          ddl-auto: update
        show-sql: true

      config:
        import: configserver:http://localhost:9091

