    server:
      port: 8081


    spring:
      datasource:
        url: jdbc:mysql://localhost:3306/microservices_tables
        username: root
        password: root
        driver-class-name: com.mysql.cj.jdbc.Driver

      application:
        name: USER-SERVICE

      jpa:
        hibernate:
          ddl-auto: update
        show-sql: true

      config:
        import: configserver:http://localhost:9091


    management:
      health:
        circuitbreakers:
          enable: true
      endpoints:
        web:
          exposure:
            include: health

      endpoint:
         health:
           show-details: always


    resilience4j:
      circuitbreaker:
        instances:
          ratingHotelBreaker:
            registerHealthIndicator: true
            eventConsumerBufferSize: 10
            failureRateThreshold: 50
            minimumNumberOfCalls: 5
            automaticTransitionFromOpenToHalfOpenEnabled: true
            waitDurationInOpenState: 6s
            permittedNumberOfCallsInHalfOpenState: 3
            slidingWindowSize: 10
            slidingWindowType: COUNT_BASED

      retry:
        instances:
          ratingUserRetry:
            max-attempts: 3
            wait-duration: 5s

