    spring:
      data:
        mongodb:
          uri: mongodb://localhost:27017
          database: microservice
      application:
        name: RATING-SERVICE

      config:
        import: configserver:http://localhost:9091

    server:
      port: 8084





